#!/usr/bin/env python
# Le noyau C++ de la grille (Modules de la simulation et le C++, section 3) : une GDExtension bâtie sur godot-cpp.
#   cd cpp ; python -m SCons platform=windows target=template_release arch=x86_64 build_profile=build_profile.json
# La bibliothèque sort dans godot/addons/sensen_grille/bin/ ; tools/build_cpp.ps1 enchaîne tout (vcvars, godot-cpp, scons).
import os

env = SConscript("godot-cpp/SConstruct")
env.Append(CPPPATH=["src/"])
if env.get("is_msvc", False):
    env.Append(CXXFLAGS=["/utf-8"])   # les commentaires sont en UTF-8 accentué
sources = Glob("src/*.cpp")
libname = "libsensen_grille{}{}".format(env["suffix"], env["SHLIBSUFFIX"])
library = env.SharedLibrary("../godot/addons/sensen_grille/bin/" + libname, source=sources)
Default(library)
